print('We learn Python language')
print("we learn Python language")
print('Soon', 'I', 'will', 'programming', 'in', 'pyton', 'language')
print('1', '2', '3', '4')
print('What a beautiful date')
print('I wont to work')
print('What a beautiful date')
print()
print('I wont to work')
print('In this text I use "double" bre')
print("In this text I use 'one' brekets")
print('4', '8', '15', '16', '23', '42')
print('4')
print('8')
print('15')
print('16')
print('23')
print('42')
print('*')
print('**')
print('***')
print('****')
print('*****')
print('******')
print('*******')



